#!/bin/bash

# Automatic Colorization Wrapper
# Usage: ./colorize_auto <target_image> [output_image]

if [ "$#" -lt 1 ]; then
    echo "Usage: ./colorize_auto <target_image> [output_image]"
    echo "Example: ./colorize_auto sample_videos/clips/v32/1415.png"
    exit 1
fi

TARGET=$1
OUTPUT=$2

if [ -z "$OUTPUT" ]; then
    python3 colorize_auto.py --target "$TARGET"
else
    python3 colorize_auto.py --target "$TARGET" --output "$OUTPUT"
fi
